"""Read-only current-library migration reports."""

from __future__ import annotations

import csv
import json
import os
from dataclasses import dataclass
from hashlib import sha256
from pathlib import Path
from tempfile import NamedTemporaryFile
from typing import Final, override

from music_ingest.inspectors.flac import inspect_flac
from music_ingest.inspectors.mp3 import inspect_mp3

AUDIO_SUFFIXES: Final = frozenset(
    {'.aac', '.aiff', '.alac', '.ape', '.flac', '.m4a', '.mp3', '.ogg', '.opus', '.wav', '.wma'}
)
REPORT_FILENAMES: Final = ('summary.json', 'review.csv', 'proposals.jsonl')


@dataclass(frozen=True, slots=True)
class DryRunMutationError(Exception):
    """The dry-run boundary detected a source-tree write or unsafe report location."""

    description: str

    @override
    def __str__(self) -> str:
        return self.description


@dataclass(frozen=True, slots=True)
class SourceFingerprint:
    """Immutable filesystem identity used to prove a scan did not mutate a source."""

    sha256: str
    size: int
    modified_ns: int


@dataclass(frozen=True, slots=True)
class MutationGuard:
    """Capture and verify all regular source files around a dry-run operation."""

    source_root: Path
    fingerprints: dict[Path, SourceFingerprint]

    @classmethod
    def capture(cls, source_root: Path) -> MutationGuard:
        """Return a complete source-tree identity snapshot before report generation."""
        return cls(source_root, _fingerprints(source_root))

    def verify(self) -> None:
        """Raise when files, timestamps, or content differ from the captured state."""
        if _fingerprints(self.source_root) != self.fingerprints:
            raise DryRunMutationError('source changed during dry-run')


@dataclass(frozen=True, slots=True)
class DryRunReports:
    """The three stable artifacts generated by one scan."""

    summary: Path
    review: Path
    proposals: Path


@dataclass(frozen=True, slots=True)
class ScanRecord:
    """A content-free source observation safe for review reports."""

    path: str
    kind: str
    sha256: str
    size: int
    modified_ns: int
    finding: str


def run_dry_run(source_root: Path, report_directory: Path) -> DryRunReports:
    """Scan supported library entries and emit review artifacts without source mutation."""
    source = source_root.resolve(strict=True)
    reports = report_directory.resolve()
    if reports.is_relative_to(source):
        raise DryRunMutationError('report directory must be outside the source tree')
    guard = MutationGuard.capture(source)
    records = tuple(_scan_file(source, path) for path in _source_files(source))
    guard.verify()
    reports.mkdir(parents=True, exist_ok=True)
    summary, review, proposals = (reports / filename for filename in REPORT_FILENAMES)
    _write_json(summary, _summary(records))
    _write_review_csv(review, records)
    _write_proposals(proposals, records)
    guard.verify()
    return DryRunReports(summary, review, proposals)


def _source_files(source_root: Path) -> tuple[Path, ...]:
    return tuple(sorted((path for path in source_root.rglob('*') if path.is_file()), key=lambda path: path.as_posix()))


def _fingerprints(source_root: Path) -> dict[Path, SourceFingerprint]:
    return {path: _fingerprint(path) for path in _source_files(source_root)}


def _fingerprint(path: Path) -> SourceFingerprint:
    stat = path.stat()
    return SourceFingerprint(sha256(path.read_bytes()).hexdigest(), stat.st_size, stat.st_mtime_ns)


def _scan_file(source_root: Path, path: Path) -> ScanRecord:
    fingerprint = _fingerprint(path)
    suffix = path.suffix.casefold()
    kind = _file_kind(suffix)
    return ScanRecord(
        path=path.relative_to(source_root).as_posix(),
        kind=kind,
        sha256=fingerprint.sha256,
        size=fingerprint.size,
        modified_ns=fingerprint.modified_ns,
        finding=_finding(path, suffix),
    )


def _file_kind(suffix: str) -> str:
    if suffix in AUDIO_SUFFIXES:
        return 'audio'
    if suffix == '.nfo':
        return 'nfo'
    if suffix == '.lrc':
        return 'lrc'
    return 'other'


def _finding(path: Path, suffix: str) -> str:
    if suffix == '.flac':
        result = inspect_flac(path)
        return f'flac:{result.state}'
    if suffix == '.mp3':
        result = inspect_mp3(path)
        return f'mp3:{result.state}'
    if suffix == '.nfo':
        return 'nfo:preserve_for_manual_review'
    if suffix == '.lrc':
        return 'lrc:validate_before_publish'
    if suffix in AUDIO_SUFFIXES:
        return 'audio:unsupported_container_review'
    return 'other:ignored'


def _summary(records: tuple[ScanRecord, ...]) -> dict[str, int | dict[str, int]]:
    kinds = {kind: sum(record.kind == kind for record in records) for kind in ('audio', 'lrc', 'nfo')}
    return {'files_scanned': len(records), 'by_kind': kinds}


def _write_json(destination: Path, payload: dict[str, int | dict[str, int]]) -> None:
    _atomic_write(destination, json.dumps(payload, ensure_ascii=True, indent=2, sort_keys=True) + '\n')


def _write_review_csv(destination: Path, records: tuple[ScanRecord, ...]) -> None:
    with NamedTemporaryFile('w', encoding='utf-8', newline='', dir=destination.parent, delete=False) as temporary:
        writer = csv.DictWriter(temporary, fieldnames=('path', 'kind', 'finding', 'sha256', 'size', 'modified_ns'))
        writer.writeheader()
        for record in records:
            writer.writerow(
                {
                    'path': record.path,
                    'kind': record.kind,
                    'finding': record.finding,
                    'sha256': record.sha256,
                    'size': record.size,
                    'modified_ns': record.modified_ns,
                }
            )
        temporary_path = Path(temporary.name)
    os.replace(temporary_path, destination)


def _write_proposals(destination: Path, records: tuple[ScanRecord, ...]) -> None:
    lines = tuple(
        json.dumps(
            {'path': record.path, 'proposal': 'review_one_album_at_a_time', 'reason': record.finding},
            ensure_ascii=True,
            sort_keys=True,
        )
        for record in records
        if record.kind != 'other'
    )
    _atomic_write(destination, '\n'.join(lines) + ('\n' if lines else ''))


def _atomic_write(destination: Path, content: str) -> None:
    with NamedTemporaryFile('w', encoding='utf-8', dir=destination.parent, delete=False) as temporary:
        _ = temporary.write(content)
        temporary_path = Path(temporary.name)
    os.replace(temporary_path, destination)
