"""squashed baseline

Revision ID: 20260810_0002
Revises:
Create Date: 2026-08-10 20:46:58.704187
"""

# pyright: reportUnusedCallResult=false

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '20260810_0002'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'genre_catalog',
        sa.Column('musicbrainz_id', sa.String(length=64), nullable=False),
        sa.Column('source_name', sa.String(length=255), nullable=False),
        sa.Column('display_name', sa.String(length=255), nullable=False),
        sa.Column('normalized_key', sa.String(length=255), nullable=False),
        sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('musicbrainz_id'),
        sa.UniqueConstraint('source_name'),
    )
    op.create_index(op.f('ix_genre_catalog_normalized_key'), 'genre_catalog', ['normalized_key'], unique=False)
    op.create_table(
        'library_records',
        sa.Column('id', sa.String(length=96), nullable=False),
        sa.Column('musicbrainz_recording_id', sa.String(length=36), nullable=True),
        sa.Column('musicbrainz_release_id', sa.String(length=36), nullable=True),
        sa.Column('musicbrainz_artist_id', sa.String(length=36), nullable=True),
        sa.Column('source_state', sa.String(length=32), nullable=False),
        sa.Column('processing_state', sa.String(length=32), nullable=False),
        sa.Column('match_state', sa.String(length=32), nullable=False),
        sa.Column('publication_state', sa.String(length=32), nullable=False),
        sa.Column('metadata_state', sa.String(length=32), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('musicbrainz_recording_id'),
    )
    op.create_table(
        'provider_schedules',
        sa.Column('provider_name', sa.String(length=64), nullable=False),
        sa.Column('next_start_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
        sa.Column('lease_token', sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint('provider_name'),
    )
    op.create_table(
        'provider_snapshots',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('provider_name', sa.String(length=64), nullable=False),
        sa.Column('request_hash', sa.String(length=64), nullable=False),
        sa.Column('request_descriptor', sa.Text(), nullable=False),
        sa.Column('response_sha256', sa.String(length=64), nullable=False),
        sa.Column('response_body', sa.LargeBinary(), nullable=True),
        sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('outcome', sa.String(length=32), nullable=False),
        sa.Column('state', sa.String(length=32), nullable=False),
        sa.Column('age_seconds', sa.Integer(), nullable=True),
        sa.Column('http_status', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'runtime_settings',
        sa.Column('key', sa.String(length=64), nullable=False),
        sa.Column('value', sa.Text(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('key'),
    )
    op.create_table(
        'source_records',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('source_path', sa.Text(), nullable=False),
        sa.Column('device', sa.BigInteger(), nullable=False),
        sa.Column('inode', sa.BigInteger(), nullable=False),
        sa.Column('size_bytes', sa.BigInteger(), nullable=False),
        sa.Column('sha256', sa.String(length=64), nullable=False),
        sa.Column('duration_seconds', sa.Integer(), nullable=True),
        sa.Column('origin', sa.String(length=16), nullable=False),
        sa.Column('intake_state', sa.String(length=32), nullable=False),
        sa.Column('library_record_id', sa.String(length=96), nullable=True),
        sa.Column('disappeared_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['library_record_id'],
            ['library_records.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'artwork_hash_observations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source_id', sa.String(length=64), nullable=False),
        sa.Column('sha256', sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ['source_id'],
            ['source_records.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'candidate_evidence',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source_id', sa.String(length=64), nullable=False),
        sa.Column('candidate_key', sa.String(length=255), nullable=False),
        sa.Column('evidence', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ['source_id'],
            ['source_records.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'fingerprint_evidence',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source_id', sa.String(length=64), nullable=False),
        sa.Column('state', sa.String(length=32), nullable=False),
        sa.Column('fingerprint', sa.Text(), nullable=True),
        sa.Column('duration_seconds', sa.Float(), nullable=True),
        sa.Column('tool_version', sa.String(length=64), nullable=True),
        sa.Column('output_sha256', sa.String(length=64), nullable=False),
        sa.Column('tool_state', sa.String(length=32), nullable=True),
        sa.Column('return_code', sa.Integer(), nullable=True),
        sa.Column('version_tool_state', sa.String(length=32), nullable=True),
        sa.Column('version_return_code', sa.Integer(), nullable=True),
        sa.Column('version_output_sha256', sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ['source_id'],
            ['source_records.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'library_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('library_record_id', sa.String(length=96), nullable=False),
        sa.Column('source_id', sa.String(length=64), nullable=True),
        sa.Column('kind', sa.String(length=64), nullable=False),
        sa.Column('state', sa.String(length=32), nullable=False),
        sa.Column('reason', sa.Text(), nullable=True),
        sa.Column('details_json', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ['library_record_id'],
            ['library_records.id'],
        ),
        sa.ForeignKeyConstraint(
            ['source_id'],
            ['source_records.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'library_metadata_revisions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('library_record_id', sa.String(length=96), nullable=False),
        sa.Column('source_id', sa.String(length=64), nullable=True),
        sa.Column('layer', sa.String(length=16), nullable=False),
        sa.Column('revision', sa.Integer(), nullable=False),
        sa.Column('tags_json', sa.Text(), nullable=False),
        sa.Column('actor', sa.String(length=128), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ['library_record_id'],
            ['library_records.id'],
        ),
        sa.ForeignKeyConstraint(
            ['source_id'],
            ['source_records.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('library_record_id', 'layer', 'revision'),
    )
    op.create_table(
        'provider_attempts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source_id', sa.String(length=64), nullable=False),
        sa.Column('provider_name', sa.String(length=64), nullable=False),
        sa.Column('outcome', sa.String(length=32), nullable=False),
        sa.Column('snapshot_sha256', sa.String(length=64), nullable=False),
        sa.Column('snapshot', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ['source_id'],
            ['source_records.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'review_decisions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source_id', sa.String(length=64), nullable=False),
        sa.Column('state', sa.String(length=32), nullable=False),
        sa.Column('rationale', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ['source_id'],
            ['source_records.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'source_tag_observations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source_id', sa.String(length=64), nullable=False),
        sa.Column('format_name', sa.String(length=32), nullable=False),
        sa.Column('tag_name', sa.String(length=128), nullable=False),
        sa.Column('value', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ['source_id'],
            ['source_records.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'jobs',
        sa.Column('id', sa.String(length=96), nullable=False),
        sa.Column('source_id', sa.String(length=64), nullable=True),
        sa.Column('kind', sa.String(length=64), nullable=False),
        sa.Column('metadata_revision_id', sa.Integer(), nullable=True),
        sa.Column('state', sa.String(length=32), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('failure_reason', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ['metadata_revision_id'],
            ['library_metadata_revisions.id'],
        ),
        sa.ForeignKeyConstraint(
            ['source_id'],
            ['source_records.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'library_publications',
        sa.Column('id', sa.String(length=96), nullable=False),
        sa.Column('library_record_id', sa.String(length=96), nullable=False),
        sa.Column('source_id', sa.String(length=64), nullable=False),
        sa.Column('path', sa.Text(), nullable=False),
        sa.Column('format_name', sa.String(length=32), nullable=False),
        sa.Column('content_sha256', sa.String(length=64), nullable=False),
        sa.Column('metadata_revision_id', sa.Integer(), nullable=True),
        sa.Column('state', sa.String(length=32), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ['library_record_id'],
            ['library_records.id'],
        ),
        sa.ForeignKeyConstraint(
            ['metadata_revision_id'],
            ['library_metadata_revisions.id'],
        ),
        sa.ForeignKeyConstraint(
            ['source_id'],
            ['source_records.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'job_attempts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('job_id', sa.String(length=96), nullable=False),
        sa.Column('attempt_number', sa.Integer(), nullable=False),
        sa.Column('state', sa.String(length=32), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['job_id'],
            ['jobs.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('job_id', 'attempt_number', name='uq_job_attempt_number'),
    )
    op.create_table(
        'webhook_receipts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('event_fingerprint', sa.String(length=64), nullable=False),
        sa.Column('provider_name', sa.String(length=64), nullable=False),
        sa.Column('payload_json', sa.Text(), nullable=False),
        sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('job_id', sa.String(length=96), nullable=True),
        sa.ForeignKeyConstraint(
            ['job_id'],
            ['jobs.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('event_fingerprint'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook_receipts')
    op.drop_table('job_attempts')
    op.drop_table('library_publications')
    op.drop_table('jobs')
    op.drop_table('source_tag_observations')
    op.drop_table('review_decisions')
    op.drop_table('provider_attempts')
    op.drop_table('library_metadata_revisions')
    op.drop_table('library_events')
    op.drop_table('fingerprint_evidence')
    op.drop_table('candidate_evidence')
    op.drop_table('artwork_hash_observations')
    op.drop_table('source_records')
    op.drop_table('runtime_settings')
    op.drop_table('provider_snapshots')
    op.drop_table('provider_schedules')
    op.drop_table('library_records')
    op.drop_index(op.f('ix_genre_catalog_normalized_key'), table_name='genre_catalog')
    op.drop_table('genre_catalog')
    # ### end Alembic commands ###
