# ruff: noqa: E501
review_page_template = """<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Music review desk</title>
<style>
:root{--ink:#17202a;--muted:#66727d;--paper:#f4f1eb;--panel:#fffdf8;--line:#d9d3c9;--accent:#bd4b2d;--ok:#2f6b55;--space:16px}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 8% 0,#fffaf0 0,#f4f1eb 42%,#e7e0d5 100%);color:var(--ink);font:16px/1.5 ui-sans-serif,system-ui,sans-serif}
main{max-width:1180px;margin:0 auto;padding:48px 24px}header{display:flex;justify-content:space-between;align-items:end;gap:var(--space);border-bottom:1px solid var(--line);padding-bottom:24px}h1{font:600 40px/1.05 Georgia,serif;letter-spacing:-.03em;margin:0}h2{font:600 22px Georgia,serif;margin:0 0 12px}.eyebrow{color:var(--accent);font:700 12px ui-monospace,monospace;letter-spacing:.12em;text-transform:uppercase}.lede{color:var(--muted);max-width:52ch}.grid{display:grid;grid-template-columns:280px 1fr;gap:24px;margin-top:24px}.panel{background:color-mix(in srgb,var(--panel) 88%,transparent);border:1px solid var(--line);border-radius:12px;padding:var(--space);box-shadow:0 12px 30px #5e514318}.panel strong{display:block}.state{color:var(--ok);font:700 12px ui-monospace,monospace;text-transform:uppercase}.section{margin-top:24px}.actions{display:flex;flex-wrap:wrap;gap:8px}.actions button{border:1px solid var(--ink);border-radius:999px;background:var(--ink);color:#fff;padding:8px 12px;cursor:pointer}.actions button:hover{background:var(--accent);border-color:var(--accent)}.evidence{display:grid;grid-template-columns:1fr 1fr;gap:12px}.evidence pre{margin:0;white-space:pre-wrap;background:#f0ebe2;border-radius:8px;padding:12px;color:#3c454c}.audit{border-left:3px solid var(--accent);padding-left:12px;color:var(--muted)}.queue-item{display:block;width:100%;text-align:left;border:0;border-bottom:1px solid var(--line);background:transparent;padding:12px 0;color:var(--ink);cursor:pointer}.queue-item:hover,.queue-item[aria-current=true]{color:var(--accent)}label{display:block;color:var(--muted);font-size:14px;margin-top:8px}input{width:100%;border:1px solid var(--line);border-radius:6px;background:#fff;padding:8px;font:inherit}.notice{color:var(--accent);min-height:24px}@media(max-width:760px){main{padding:24px 16px}header{display:block}.grid{grid-template-columns:1fr}.evidence{grid-template-columns:1fr}h1{font-size:32px}}
</style></head>
<body><main><header><div><div class="eyebrow">Local-only decision desk</div><h1>Review the evidence. Keep the audio untouched.</h1><p class="lede">Every observation, proposed field, provider snapshot, fingerprint, candidate, and decision stays visible and reversible.</p></div><div id="state" class="state">loading</div></header>
<div class="grid"><aside class="panel"><h2>Queue</h2><p class="lede">Low-confidence matches never promote themselves.</p><div id="queue" aria-live="polite"></div></aside>
<section><div class="panel"><h2>Evidence & diff</h2><div id="evidence" class="evidence"><p class="lede">Select a queue item to inspect evidence.</p></div></div>
<div class="panel section"><h2>Attention actions</h2><p id="notice" class="notice" role="status"></p><div class="evidence"><div><label for="artist">Artist</label><input id="artist" name="artist"><label for="release-title">Release title</label><input id="release-title" name="release_title"></div><div><label for="musicbrainz">MusicBrainz URL or ID</label><input id="musicbrainz" name="musicbrainz_id"></div></div><div class="actions" id="actions"><button data-action="attach">Attach MusicBrainz URL / ID</button><button data-action="reject">Reject</button><button data-action="defer">Defer</button><button data-action="rematch">Rematch</button></div></div>
<div class="panel section"><h2>Audit history</h2><div id="audit" class="audit">Select an item to inspect its append-only history.</div></div></section></div></main>
<script>
const queueElement=document.querySelector('#queue');const evidenceElement=document.querySelector('#evidence');const auditElement=document.querySelector('#audit');const stateElement=document.querySelector('#state');const noticeElement=document.querySelector('#notice');const actionPaths={attach:'actions/attach'};let sourceId=null;
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
const jsonBlock=value=>escapeHtml(JSON.stringify(value,null,2));
async function loadQueue(){const response=await fetch('/api/review/queue');const payload=await response.json();queueElement.innerHTML=payload.items.length?payload.items.map(item=>`<button class="queue-item" data-source-id="${escapeHtml(item.source_id)}" aria-current="${item.source_id===sourceId}">${escapeHtml(item.source_id.slice(0,12))} · ${escapeHtml(item.state)}</button>`).join(''):'<p class="lede">No review items.</p>';if(!sourceId&&payload.items[0])await loadDetail(payload.items[0].source_id);}
async function loadDetail(id){sourceId=id;const response=await fetch(`/api/review/items/${sourceId}`);const detail=await response.json();const originalFields=detail.original;const auditHistory=detail.audit;stateElement.textContent=detail.state;document.querySelector('#artist').value=detail.proposed.artist||'';document.querySelector('#release-title').value=detail.proposed.release_title||'';document.querySelector('#musicbrainz').value=detail.musicbrainz_id||'';evidenceElement.innerHTML=`<div><strong>Original observations</strong><pre>${jsonBlock(originalFields)}</pre><strong>Provider / cache state</strong><pre>${jsonBlock(detail.provider)}</pre></div><div><strong>Proposed fields</strong><pre>${jsonBlock(detail.proposed)}</pre><strong>Diff, fingerprints &amp; candidates</strong><pre>${jsonBlock({diff:detail.diff,fingerprints:detail.fingerprints,candidates:detail.candidates})}</pre></div>`;auditElement.innerHTML=auditHistory.length?auditHistory.map(entry=>`<p><strong>${escapeHtml(entry.action)}</strong> by ${escapeHtml(entry.actor)}<br><small>before ${jsonBlock(JSON.parse(entry.before))}<br>after ${jsonBlock(JSON.parse(entry.after))}</small></p>`).join(''):'No decisions yet. Rematching preserves the previous-publish snapshot.';document.querySelectorAll('.queue-item').forEach(item=>item.setAttribute('aria-current',String(item.dataset.sourceId===sourceId)));}
async function submitAction(action){if(!sourceId){noticeElement.textContent='Select a queue item first.';return;}const body={artist:document.querySelector('#artist').value,release_title:document.querySelector('#release-title').value,musicbrainz_id:document.querySelector('#musicbrainz').value};const actionPath=actionPaths[action]||`actions/${action}`;const response=await fetch(`/api/review/items/${sourceId}/${actionPath}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const payload=await response.json();noticeElement.textContent=response.ok?`Saved: ${payload.state}`:payload.detail||'Action failed';await loadDetail(sourceId);await loadQueue();}
queueElement.addEventListener('click',event=>{const item=event.target.closest('[data-source-id]');if(item)loadDetail(item.dataset.sourceId);});document.querySelector('#actions').addEventListener('click',event=>{const button=event.target.closest('[data-action]');if(button)submitAction(button.dataset.action);});loadQueue().catch(error=>{noticeElement.textContent=`Unable to load review queue: ${error.message}`;});
</script></body></html>"""

REVIEW_PAGE = review_page_template.replace(
    '</main>',
    """<section class="panel section" id="release-review"><h2>Release review</h2><p class="lede">Published releases remain editable. Changes create a new final revision and republish automatically.</p><div id="release-queue"></div><div id="release-detail" class="evidence"><p class="lede">Select a release to inspect Original tags, Analyzed candidates, and Final tags.</p></div><label for="release-final-title">Final title</label><input id="release-final-title" name="release_final_title"><div class="actions"><button data-release-action="edit">Save final title</button><button data-release-action="republish">Republish</button><button data-release-action="rollback">Rollback</button></div></section>""",
).replace(
    '</body>',
    """<script>
const releaseQueueElement=document.querySelector('#release-queue');const releaseDetailElement=document.querySelector('#release-detail');let releaseId=null;let releaseRevision=null;
async function loadReleaseQueue(){const response=await fetch('/api/release-review/queue');const payload=await response.json();releaseQueueElement.innerHTML=payload.items.map(item=>`<button class="queue-item" data-release-id="${escapeHtml(item.release_id)}">${escapeHtml(item.incoming_folder)} · ${escapeHtml(item.publication_state)} · ${escapeHtml(item.review_state)}</button>`).join('')||'<p class="lede">No published releases.</p>';if(!releaseId&&payload.items[0])await loadReleaseDetail(payload.items[0].release_id);}
async function loadReleaseDetail(id){releaseId=id;const response=await fetch(`/api/release-review/releases/${releaseId}`);const detail=await response.json();const track=detail.tracks[0];releaseRevision=track.final_revision;document.querySelector('#release-final-title').value=track.layers.final.TITLE||'';releaseDetailElement.innerHTML=`<div><strong>Original tags</strong><pre>${jsonBlock(track.layers.original)}</pre><strong>Analyzed candidates</strong><pre>${jsonBlock(detail.candidates)}</pre></div><div><strong>Final tags</strong><pre>${jsonBlock(track.layers.final)}</pre><strong>Publication & revision</strong><pre>${jsonBlock({publication:detail.publication,revision:releaseRevision,audit:detail.audit})}</pre></div>`;}
async function submitReleaseAction(action){if(!releaseId||releaseRevision===null)return;const endpoint=action==='edit'?`/api/release-review/releases/${releaseId}/tags`:`/api/release-review/releases/${releaseId}/${action}`;const body=action==='edit'?{revision:releaseRevision,tags:{TITLE:document.querySelector('#release-final-title').value}}:{revision:releaseRevision};const response=await fetch(endpoint,{method:action==='edit'?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});noticeElement.textContent=response.ok?`Release ${action}ed.`:(await response.json()).detail||'Release action failed';if(response.ok){await loadReleaseDetail(releaseId);await loadReleaseQueue();}}
releaseQueueElement.addEventListener('click',event=>{const item=event.target.closest('[data-release-id]');if(item)loadReleaseDetail(item.dataset.releaseId);});document.querySelector('#release-review .actions').addEventListener('click',event=>{const button=event.target.closest('[data-release-action]');if(button)submitReleaseAction(button.dataset.releaseAction);});loadReleaseQueue().catch(error=>{noticeElement.textContent=`Unable to load release queue: ${error.message}`;});
</script></body>""",
)
