"""Database boundary: SQLAlchemy metadata, entities, and entity queries."""

from music_ingest.models.db import Base
from music_ingest.models.entities import (
    ArtworkRecord,
    CandidateRecord,
    DecoderEvidenceRecord,
    FingerprintRecord,
    GenreCatalogRecord,
    JobAttemptRecord,
    JobRecord,
    ProviderAttemptRecord,
    ProviderCandidateRunRecord,
    ProviderScheduleRecord,
    ProviderSnapshotRecord,
    ReviewDecisionRecord,
    RuntimeSettingRecord,
    SourceAssociationOverrideRecord,
    SourceRecord,
    SourceRecordingAssignmentRecord,
    SourceRootRecord,
    SourceTagRecord,
    StorageConfigRecord,
    WebhookReceiptRecord,
)
from music_ingest.models.library import (
    EffectiveSourceDecisionRecord,
    LibraryEventRecord,
    LibraryMetadataRevisionRecord,
    LibraryPublicationRecord,
    LibraryRecord,
    LibraryRecordConsolidationRecord,
    PublicationAttemptRecord,
)

__all__ = [
    'ArtworkRecord',
    'Base',
    'CandidateRecord',
    'DecoderEvidenceRecord',
    'EffectiveSourceDecisionRecord',
    'FingerprintRecord',
    'GenreCatalogRecord',
    'JobAttemptRecord',
    'JobRecord',
    'LibraryEventRecord',
    'LibraryMetadataRevisionRecord',
    'LibraryPublicationRecord',
    'LibraryRecord',
    'LibraryRecordConsolidationRecord',
    'PublicationAttemptRecord',
    'ProviderAttemptRecord',
    'ProviderCandidateRunRecord',
    'ProviderScheduleRecord',
    'ProviderSnapshotRecord',
    'ReviewDecisionRecord',
    'RuntimeSettingRecord',
    'SourceRecord',
    'SourceAssociationOverrideRecord',
    'SourceRecordingAssignmentRecord',
    'SourceRootRecord',
    'SourceTagRecord',
    'StorageConfigRecord',
    'WebhookReceiptRecord',
]
